---
- name:         Get list of Network endpoints.
  register:     openstack_network_endpoints
  changed_when: no
  command:      openstack endpoint list -f value -c Interface --service network

- name:    Create Network endpoints.
  command: 'openstack endpoint create --region {{ region }} network {{ item.key }} {{ item.value }}'
  when:    '"{{ item.key }}" not in openstack_network_endpoints.stdout'
  with_dict:
    public:   'http://{{ host }}:9696'
    internal: 'http://{{ host }}:9696'
    admin:    'http://{{ host }}:9696'
