---
- name:         Get list of services.
  register:     openstack_services
  changed_when: no
  command:      openstack service list -f value -c Type

- name:    Create Network service.
  command: openstack service create --name neutron --description "OpenStack Networking" network
  when:    '"network" not in openstack_services.stdout'
