---
- name:         Get list of users.
  register:     openstack_users
  changed_when: no
  command:      openstack user list -f value -c Name --domain default

- name:    Create Network user.
  command: 'openstack user create --domain default --password {{ keystone_password }} neutron'
  when:    '"neutron" not in openstack_users.stdout'

- name:         Assign role to Network user.
  changed_when: no
  command:      'openstack role add --project service --user neutron admin'
